### PR TITLE
updated crypto-rpc reference

### PR DESCRIPTION
**Pull request by escottalexander**

### CODE REVIEW

**Comment by escottalexander** [comment]
@kajoseph, I updated to latest crypto-rpc commit and merged in latest from master.

**Review by kajoseph — CHANGES_REQUESTED** [review]
This will break our node v8 compatibility. We'll need to bump the minimum node version in `bitcore-node/package.json` to >=12.0.0

**Review by kajoseph — APPROVED** [review]
ACK

**Comment by escottalexander** [comment]
Merged in latest from master.

**Review by kajoseph — APPROVED** [review]

**Review by nitsujlangston — APPROVED** [review]

**Pull request merged**
