### PR TITLE
xversion placeholder to maintain compatibility with BUcash1.5.1

### PR DESCRIPTION
**Pull request by imaginaryusername**
xversion is a new message type in BUCash 1.5.1, this patch prevents bitcore error when used with it.

### CODE REVIEW

**Comment by gandrewstone** [comment]
is this happening because bitcore does not tolerate any unknown-type messages, or is there some specific problem with xversion?

**Comment by imaginaryusername** [comment]
It did not seem to tolerate any unknown messages, which is why my "dummy" worked, I think - it's modified from `verack.js`. However I'm unsure how to fix the failed test which seems to be for wallet service.

**Comment by zander** [comment]
According to the p2p spec clients should ignore messages they don't understand.

Maybe that is an alternative route that is easier to make working.

**Comment by matiu** [comment]
thanks for the PR. 

CI is broken since last week, we are trying to fix it. The mono repo migration was a real challenge :)

**Pull request merged**
