### PR TITLE
Cleanup/requirements

### PR DESCRIPTION
**Pull request by thofmann**
These are nonfunctional changes. I only changed some of the requirement variable names for consistency.

### CODE REVIEW

**Comment by braydonf** [comment]
The style guidelines look like they are conflicting on this one between [G0](https://github.com/bitpay/bitcore/blob/master/CONTRIBUTING.md#g0---default-to-felixges-style-guide) and [G6](https://github.com/bitpay/bitcore/blob/master/CONTRIBUTING.md#g6---naming-utility-namespaces).

**Comment by eordano** [comment]
You're right @braydonf 

As G6 is quite specific, should we add a note stating that this is an exception to G0?

**Comment by eordano** [comment]
@braydonf actually, felix's style guide doesn't mention anything about Namespaces (which is a more appropriate name for these utils). I think there's no conflict in that case

**Comment by eordano** [comment]
Overall ACK; I'll merge because the coverall decrease doesn't make sense.

**Pull request merged**
