### PR TITLE
Fixed small issue of opts not propagating for multisig noSorting

### PR DESCRIPTION
**Pull request by patwhite**
Fixed a very small issue with noSorting opts param not propagating to a buildMultisigOut call.

### CODE REVIEW

**Comment by patwhite** [comment]
Alright @micahriggan, passing now

**Comment by micahriggan** [comment]
Thanks!

**Comment by patwhite** [comment]
Is there a prerelease version somewhere I can reference to use this now? Having trouble building it locally to use. Thanks man!

**Comment by micahriggan** [comment]
It hasn't been npm published, so you'd have to reference it relatively, or by using the github url in the package.json ( I think )

**Comment by patwhite** [comment]
ya, can't reference this directly from npm since this switched to a mono repo, so you end up having to submodule then reference locally. But, all good, i'll figure it out. Thanks man!

**Pull request merged**
