### PR TITLE
fix wallet key size

### PR DESCRIPTION
**Pull request by matiu**
in bitcore-client.

### CODE REVIEW

**Comment by micahriggan** [comment]
shouldn't the private key itself do logic, so we never return a buffer that is too small

**Comment by matiu** [comment]
Not sure.


 It is not clear to me that a priv key of up to 32 bytes need always to
alloc a 32 byte buffer. It seems more an issue of the receiving function.

**Comment by micahriggan** [comment]
Gotcha, so if we did  new PrivateKey(key.toBuffer())

Would that result in a different key?

**Comment by micahriggan** [comment]
Even more interesting is the comment on toBuffer

https://github.com/bitpay/bitcore/blob/68c4ea440089668dfa10a9695f9c971d34d0b011/packages/bitcore-lib/lib/privatekey.js#L339

**Comment by matiu** [comment]
:)

Sounds good. Lets do it that way then.

**Comment by matiu** [comment]
udpated.

**Pull request merged**
