### PR TITLE
WIP bitcore docker

### PR DESCRIPTION
**Pull request by nitsujlangston**
`docker run bitcore node`
`docker run bitcore bws`

### CODE REVIEW

**Comment by micahriggan** [comment]
Why do there need to be two Dockerfiles? The current one is capable of running the CI and bitcore node

**Comment by nitsujlangston** [comment]
> Why do there need to be two Dockerfiles? The current one is capable of running the CI and bitcore node

@micahriggan !! Just a WIP, working on getting bitcore api/sync and bws api/other services all runnable from single container. Broke out the ci one to get the chrome stuff out of there, but open to suggestions on how to extend them from single dockerfile

**Comment by nitsujlangston** [comment]
End goal being an image which can be run with different commands and arguments to create an entire kubernetes set up running all of it

**Comment by micahriggan** [comment]
Nice!

https://github.com/bitpay/bitcore/pull/2706/files

I messed around a lil bit with that, I made additional Docker files for the specific services. 

So bitcore-node-api just extends the current Dockerfile

The chrome stuff was only in there for Insight afaik, it might not be needed anymore.

The thing I couldn't figure out was how to test the kubernetes files without having them mutate with machine specific info. Let me know if you get that figured out

**Comment by sondreb** [comment]
> Nice!
> 
> https://github.com/bitpay/bitcore/pull/2706/files
> 
> I messed around a lil bit with that, I made additional Docker files for the specific services.
> 
> So bitcore-node-api just extends the current Dockerfile
> 
> The chrome stuff was only in there for Insight afaik, it might not be needed anymore.
> 
> The thing I couldn't figure out was how to test the kubernetes files without having them mutate with machine specific info. Let me know if you get that figured out

Is there a point in making additional dockerfiles for the different modues, e.g. you made "Dockerfile-bitcore-node-api" which does:

```
CMD ["node", "/bitcore/packages/bitcore-node/build/src/workers/api.js"]
```

If the main dockerfile only contains at the bottom:

```
ENTRYPOINT [ "npm", "run" ]
```

Then you can run the different npm tasks with command in your compose files for Kubernetes/Docker:

```
command: ["node"]
```

**Comment by micahriggan** [comment]
@sondreb I think what you're suggesting makes more sense than the way I did it with multiple files.

I just didn't know how to pass something into the entry point like that.

 I think at the time I was thinking you could publish each one so people could run the specific service they wanted, but seems like that could be accomplished with what you're suggesting.

**Pull request closed without merging**
