### PR TITLE
Reusable address for Bitcoin Cash

### PR DESCRIPTION
**Pull request by matiu**
Implements sending and receiving using Reusable (stealth) Address in:
  * Bitcore-Wallet-Service (BWS)
  *  Bitcore-Wallet-Client  (BWC)
  *  Bitcore-Wallet-Cli Copay Wallet Command Line.

This is a requisite for address Reusable addresses to Copay / Bitpay Wallet.   Bitcore-wallet-cli is compatible with Copay's backend (BWS). 

Who it works?
==========
Get a stealth address from an existing wallet:
```
$ ./wallet-stealth-address -f wallet2.json
* Stealth Address 9VQQXJX49PPUWLEPS2QHY89PKDG3FY9W89EL46WJQPLA025XP4RAFPKLQYPGVY82Y38DN6GWV0DGPME6CKPPA8QXC3VY4G6J344XRXC9L3TEN9SPQQ
```

from any other wallet, send funds to it!

```
./wallet-send -f wallet2.json 9VQQ80NEX6CALLF0SRMGRSMFVXMKD30354S0UKMFT5C2HJHTDAFTH7WEQYPYRTTWFJ3ES6XUFS3FQDWLZ4LQNF9WR6LDWV38FDNPH4RHU34TCLGPQQ  6000 
```

done!

Implementation details
================
 * Address are encoded using Base32, which is Bitcoin Cash friendly, and allows to use alphanumeric encoding in QR codes.
 * Spend key is derived from each copayer's xPriv using path: m/44'/<coin>'/0'/2/1
 * P2SH multisig address MUST sort pubkeys before generating the redeem script (this is the default in  bitcore-lib).
 * Scan key PRIVATE is derived from each copayer's xPub using path: m/44'/<coin>'/0'/2/0
Since the scan private key only is used to monitor the blockchain, it makes sense to use a f(xPubs keys) to create it, and no need to do any coordination between copayers to arrive a new shared secret.

 * Reusable address for up to 2-3 or 3-3 wallets are around 220chars and can fit a QR code. M-of-N Wallets with N>3 will have an address too big for QRs. Since those wallets are really rare, I don't see a problem there, even restricting reusable addresses to N=3 max.

TODO
====
- [ ] add incomming stealth TXs to wallet balance / getUtxo
- [ ] output suffling (disabled for now)
- [ ] refactor + optimize tx detection. This is VERY IN WIP but it is working in BlockChainMonitor
- [ ] use prefixes for detection / broadcasting
- [ ] detect OLD/mined incoming stealth txs
- [ ] use https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/op_return-prefix-guideline.md

Acknowledges
===========
@petertodd for creating the schema and writing the BIP athttps://raw.githubusercontent.com/genjix/bips/master/bip-stealth.mediawiki
@yemel for writing the first Bitcore-stealth implementation in 2015.
@markblundeberg and @cpacia for advice and discussion.
@monsterbitar for pushing CashAddr to live and chain reacting this work.

### CODE REVIEW

**Comment by zquestz** [comment]
Is there a BIP or BUIP that describes these changes in more detail?

**Comment by matiu** [comment]
@zquestz no yet. The implementation is 90% the original Todd's schema. We only updated the addr encoding to base32. Will write the differences when it is closed to be landed.

**Comment by SwenVanZanten** [comment]
Sorry for asking this annoying question 🙉 but is there an eta for this pr?

**Comment by matiu** [comment]
closing this for now. Hopefully we will be able to work on this soon.

**Pull request closed without merging**
