### PR TITLE
Added Chrome Browser Test if Available.

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by braydonf** [comment]
Okay, updated to use `karma-detect-browsers` and will launch additional browsers if available. Chrome and Firefox working locally.

**Comment by braydonf** [comment]
Ready for review!

**Comment by braydonf** [comment]
Found more disconnected issues when testing locally with other browsers besides chrome and firefox.

**Comment by braydonf** [comment]
Okay, so Chrome and Firefox are working. The Safari and IE tests will disconnect in the middle of the test, even locally, same issue that was happening with browserstack.

**Comment by eordano** [comment]
LGTM (@maraoz @yemel)

**Comment by maraoz** [comment]
ACK

**Pull request merged**
