### PR TITLE
Fix JS doc for publickey.js

### PR DESCRIPTION
**Pull request by dskloet**

### CODE REVIEW

**Comment by maraoz** [comment]
LGTM

**Comment by dskloet** [comment]
This is the first time I make a pull request (for any project). Is there anything else I need to do?

**Comment by braydonf** [comment]
Seems like we may have a mix between Google Closure Compiler syntax optional params and the JSDoc syntax: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values

We may want to pick one and use that consistantly.

**Comment by dskloet** [comment]
I also noticed that you were using String instead of string while the primitive JS type is called string (lower case). But I didn't touch that since it at least seemed to be consistent.

**Comment by eordano** [comment]
Congratz on your first PR!

**Comment by eordano** [comment]
@braydonf: I opened https://github.com/bitpay/bitcore/issues/1108 to discuss that

**Comment by dskloet** [comment]
Thanks :)

**Pull request merged**
