### PR TITLE
Use defaultNetwork in Script.toAddress

### LINKED ISSUE #883: Script.prototype.toAddress and Networks.defaultNetwork
Expected behavior:
```
var address = script.toAddress();
// uses the current default network
```
Current behavior:
```
var address = script.toAddress(Networks.defaultNetwork);
// requires passing the default network as an argument
```

### PR DESCRIPTION
**Pull request by yemel**
Closes #883

### CODE REVIEW

**Comment by braydonf** [comment]
If a 'testnet' address was used to instantiate a script, and the default network was 'livenet', would `script.toAddress()` return the same address?

**Comment by eordano** [comment]
No, it wouldn't. I think it's fine, we can only go so far on babysitting the user?

@braydonf please merge if you agree, otherwise let's discuss alternatives

**Comment by braydonf** [comment]
I think this should be true, in all cases:
```
var x = script.toAddress(script.fromAddress(y));
assert.equal(x, y);
```

**Comment by yemel** [comment]
`.toAddress(...)` receives a `network` object not a `script`. Do you mean:

```
assert.equal(address, script.fromAddress(address).toAddress())
```

**Comment by eordano** [comment]
That would need us to add a "network" to each script. I'd rather not :(

**Comment by braydonf** [comment]
@yemel. Yep, edited to be correct.

**Comment by braydonf** [comment]
Doesn't `Address` accept Script as input? It should be possible to then do:
```
var address = new Address(script);
```
And script.toAddress isn't needed?

**Comment by yemel** [comment]
I would like to keep the `toAddress` method on Script, mostly for convenience.

**Comment by maraoz** [comment]
ACK

**Comment by braydonf** [comment]
ACK

**Pull request merged**
