### PR TITLE
Insight prev

### PR DESCRIPTION
**Pull request by micahriggan**
Merging this in, so we can have work on both going side by side

### CODE REVIEW

**Comment by galfert** [comment]
After this has been merged, I'm getting the following warning on `npm install`:

> lerna WARN Package name "@bitpay/insight" used in multiple packages:
          	/[...]/bitcore/packages/insight-previous
	/[...]/bitcore/packages/insight

And then a little later this error:

> lerna ERR! npm run postinstall [@bitpay/insight] Output from stderr:
sh: webdriver-manager: command not found

**Comment by micahriggan** [comment]
Hi! Which folder is that happening in? Root level?

**Comment by galfert** [comment]
Hi. Yes, it's happening when running `npm install` on the bitcore repo's root.

**Comment by micahriggan** [comment]
Thanks for the report! I have pushed a commit which fixes that for me, does that resolve it for you?

**Comment by galfert** [comment]
Yes, thanks. This fixed that error for me as well.

But now I'm getting an error, because it's trying to install node-sass version 4.5.0, which doesn't seem to be compatible with Node 10.

**Comment by micahriggan** [comment]
Okay, I'm on node 8.12 I think. Do you know if there's a version that's compatible?

**Comment by skddc** [comment]
According to https://github.com/sass/node-sass/releases node 10 support was introduced in `4.9.0`. I'd just update to the latest version of it.

**Comment by micahriggan** [comment]
I updated to the latest, switched to node 10, and it appears to handle npm install without errors. 

Let me know if something else comes up.

**Pull request merged**
