### PR TITLE
Allow utxo association from bitcore-lib

### PR DESCRIPTION
**Pull request by jackbonaguro**

### CODE REVIEW

**Review by sbhatnagar30 — APPROVED** [review]
looks good, thanks

**Comment by sbhatnagar30** [comment]
@kajoseph this can be merged whenever you have time

**Review by kajoseph — APPROVED** [review]

**Comment by kajoseph** [comment]
@jackbonaguro I can't merge this until all commits are signed. There's one `Unverified` commit that's blocking the merge.

**Comment by jackbonaguro** [comment]
> @jackbonaguro I can't merge this until all commits are signed. There's one `Unverified` commit that's blocking the merge.

Fixed, I typo'ed my email locally

**Review by sbhatnagar30 — APPROVED** [review]
Looked at it again, looks good @kajoseph

**Review by kajoseph — APPROVED** [review]

**Pull request merged**
