### PR TITLE
Also check for a publickeyout in toAddress

### LINKED ISSUE #1306: toAddress() publickey out addresses
So that adding this additional case isn't needed:
```js
 var address = script.toAddress(this.db.network);
 if (!address && script.isPublicKeyOut()) {
    var pubkey = script.chunks[0].buf;
    address = Address.fromPublicKey(new PublicKey(pubkey), this.db.network);
 }
```

And can be:

```js
 var address = script.toAddress(this.db.network);
```

### PR DESCRIPTION
**Pull request by braydonf**
Fixes #1306

### CODE REVIEW

**Comment by maraoz** [comment]
~NACK. There's no actual address in a pay to public key output. It could be useful to have this tough... @jgarzik thoughts?

**Comment by braydonf** [comment]
Currently insight.bitpay.com displays this output with an address: https://insight.bitpay.com/block/00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048

**Comment by braydonf** [comment]
Just took a look at other block explorers, and the early publickey-outs are being indexed with an address (even though there technically isn't one because it's just the public key): 

https://blockchain.info/block/00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048

https://www.blocktrail.com/BTC/block/00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048

https://btc.blockr.io/block/info/1

**Comment by braydonf** [comment]
We can handle this with the block handler, closing until there is a better solution.

**Pull request closed without merging**
