### PR TITLE
Include hash in toObject/toJSON results.

### LINKED ISSUE #1308: `toObject()` and `toJSON()` missing hashes
While the hash of a transaction or block are not necessary for serialization, it may make sense to include the hash as a part of the `toJSON()` and `toObject()` results for convienience, and so that additional computation isn't needed.

### PR DESCRIPTION
**Pull request by braydonf**
Fixes #1308 and https://github.com/bitpay/bitcore-node/issues/74

### CODE REVIEW

**Comment by maraoz** [comment]
I would add a check in `fromObject` to see if the calculated hash equals the received hash

**Comment by braydonf** [comment]
Currently the hash property in `fromObject` is ignored, and the hash would then always be the computed value...

**Comment by braydonf** [comment]
Updated! The argument hash properties are checked for consistency with the calculated hash for both Transaction and BlockHeader.

**Comment by maraoz** [comment]
Nice. LGTM

**Pull request merged**
