### PR TITLE
remove inBrowser

### PR DESCRIPTION
**Pull request by fanatid**
In browserify `global` referrers to `window` -- [see docs](https://github.com/substack/browserify-handbook#global)
and check on browser detection was wrong, module `process` exists in browserify bundle

### CODE REVIEW

**Comment by braydonf** [comment]
We should also add unit tests around the check (unfortunately missing currently), and the message can be inaccurate, e.g. the versions can be the same.

**Comment by fanatid** [comment]
understand, I will try to do it in nearest days

**Comment by fanatid** [comment]
PR updated

**Comment by maraoz** [comment]
LGTM

**Comment by fanatid** [comment]
but.. may be better will be use `process.browser` instead `typeof window`, thoughts?

**Comment by fanatid** [comment]
... and I'll happy move guard to package, because I want use something like this in [coloredcoinjs-lib](http://github.com/chromaway/coloredcoinjs-lib)

**Comment by braydonf** [comment]
@fanatid: Submitted a PR, should be able to run a unit test and check that global._bitcore is defined in Node.js and browsers, and that the guard will throw an error: https://github.com/fanatid/bitcore/pull/1

**Comment by fanatid** [comment]
@braydonf thanks!

**Comment by pnagurny** [comment]
ACK

**Pull request merged**
