### PR TITLE
allow Transaction.to take array (#1334)

### LINKED ISSUE #1334: Transaction.to like Transaction.from
`Transaction.from` may accept `array`, but `Transaction.to` accept only `(address, amount)`.. I think will be helpful if `Transaction.to` could accept form like this: `[{address: string, amount: number}, ...]`, thoughts?

### PR DESCRIPTION
**Pull request by fanatid**
Resolve #1334, but need discuss.

### CODE REVIEW

**Comment by braydonf** [comment]
I think it makes sense to add this, good idea. I think it would be good to add new tests, or leave some of the tests with the chained `to` methods, as both should work.

**Comment by fanatid** [comment]
I changed some tests, now both form work at the one test for example.

**Comment by braydonf** [comment]
Also need to update the jsdocs at: https://github.com/bitpay/bitcore/pull/1345/files#diff-3ff19b4e31a68503f7ddd89615e606d7R700 to include that an array with objects with address and satoshis, can also be sent.

**Comment by fanatid** [comment]
Not sure that my jsdoc is right.

**Comment by braydonf** [comment]
Interesting, looking at the jsdocs reference, it appears correct. We haven't used typedef yet.

**Comment by maraoz** [comment]
LGTM!

**Pull request merged**
