### PR TITLE
add base to BN.fromString

### PR DESCRIPTION
**Pull request by maraoz**
I encountered a problem with `BN.fromString`. 

A quick workaround is to use BN.fromBuffer instead, but this should be fixed

### CODE REVIEW

**Comment by maraoz** [comment]
if someone wants to tackle this, they can create PRs to my branch. I can't fix this right now

**Comment by braydonf** [comment]
May be an issue with not passing a base option to BN.

**Comment by braydonf** [comment]
Still WIP?

**Comment by maraoz** [comment]
updated title

**Comment by erc155** [comment]
e2542866d1134c11920190b686be69434c092dbf

**Pull request merged**
